spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:13306/staff_db
    username: staff_app
    password: ssemchelin01!
    pool:
      max-size: 100
      validation-query: SELECT 1


logging:
  level:
    org.springframework.r2dbc.core: debug